railsprojectmodeapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :posts

  resources :sessions

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :categories

  resources :comments

  resources :likes

  resources :user_categories

  resources :mod_categories

  get '/modrequest', to: 'mod_categories#show'

  get '/analytics', to: 'analytics#index'

  get '/analytics/user', to: 'analytics#show', as: 'analytic'

  root 'posts#index'
end

railsprojectmodeapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>


    <title>Railsprojectmodeapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- CATEGORY NAVBAR START -->
    <nav>
      <div class="nav-wrapper bg-light py-1">
        <div class="left">

          <!-- MY CATEGORIES -->
          <% if logged_in? %>
            <%= link_to "My categories", '#' ,class: 'dropdown-toggle top-small', id: 'dropdownMenuButton', data: {toggle: 'dropdown'}, aria: {:'aria-haspopup' => true, :'aria-expanded' => false } %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%if current_user.categories.length > 0%>
                  <% current_user.categories.each do |cat| %>
                    <a class="dropdown-item top-small" href="<%=category_path(cat)%>"><%= cat.name%></a>
                  <%end%>
                <%else%>
                  <a class="dropdown-item" href="#">[You Have No Liked Categories]</a>
                <%end%>
              </div>
          <%end%>

          <!-- CATEGORIES LIST -->
          <% if logged_in? %>
            <% signedin_categories.each do |category| %>
              <span class="top-small"><%= link_to category.name, category_path(category) %></span>
              <% end %>
          <% else %>
            <% guest_categories.each do |category| %>
              <span class="top-small"><%= link_to category.name, category_path(category) %></span>
            <% end %>
          <% end %>
          <%= link_to "See All Categories", categories_path, class: "top-small"%>
        </div>

      </div>


    </nav>
    <!-- CATEGORY NAVBAR END -->

    <nav class="navbar navbar-light bg-primary mb-4">
      <%= link_to "HOME", root_path, class: 'btn bg-primary text-light'%>

      <% if logged_in? && current_user.admin == true %>
        <%= link_to "MY PROFILE", user_path(current_user), class: 'btn bg-primary text-light'%>
        <%= link_to "LOG OUT", logout_path, method: :delete, class: 'btn bg-primary text-light'%>
        <%= link_to "NEW POST", new_post_path, class: 'btn bg-primary text-light' %>
        <%= link_to "NEW CATEGORY", new_category_path, class: 'btn bg-primary text-light' %>
      <% elsif logged_in? %>
        <%= link_to "MY PROFILE", user_path(current_user), class: 'btn bg-primary text-light'%>
        <%= link_to "LOG OUT", logout_path, method: :delete, class: 'btn bg-primary text-light'%>
        <%= link_to "NEW POST", new_post_path, class: 'btn bg-primary text-light' %>
      <%else %>
        <%= link_to "SIGN UP", new_user_path, class: 'btn bg-primary text-light'%>
      <%end%>
    </nav>



    <div class="container-fluid">

      <% if flash[:error] %>
        <% flash[:error].each do |error| %>
        <div class="row alert-danger border mb-1" role="alert">
          <div class="col">
            <%= error %>
          </div>
        </div>
        <% end %>
        <br><br>
      <% end %>


      <div class="row mb-4">



        <!-- MAIN PAGE BODY START -->
        <div class="col-md-9">
            <%= yield %>
        </div>

        <!-- SIDE BAR BODY -->
        <div class="col-md-3 px-3">
          <div class="border px-3">

          <!-- USER INFO OR LOGIN -->
          <div class="row">
            <div class="col py-3">

              <% if logged_in? %>
                <%= image_tag "#{current_user.image_link}", class: 'img-fluid', alt: '' %>
                <%= render 'users/small_show', locals: {user: @user = current_user} %>
              <% else %>
                <div class="row text-center">
                  <div class="col py-3">
                    <%= render template: 'sessions/new', locals: {user: @user = make_user} %>
                  </div>
                </div>
              <% end %>

            </div>
          </div>


          <!-- CATEGORY DESCRIPTION -->

            <!-- CATEGORY PAGE -->
            <% Category.all.each do |category| %>
              <% if current_page?(category_path(category)) %>
                <div class="row border border-left-0 border-right-0 border-bottom-0 py-3 mb-3">
                  <div class="col">
                    <%= render 'categories/small_show', locals: {category: @category = category} %>
                  </div>
                </div>
              <% end %>
            <% end %>



            <!-- POST PAGE -->
            <% Post.all.each do |post| %>
              <% if current_page?(post_path(post)) %>


              <!-- POST INFO -->
              <div class="row border border-left-0 border-right-0 py-3">
                <div class="col">
                  <%= render 'posts/small_show', locals: {post: @post = post} %>
                </div>
              </div>

              <!-- POST CATEGORY INFO -->
              <div class="row border border-left-0 border-right-0 border-top-0 border-bottom-0 py-3 mb-3">
                <div class="col">
                  <%= render 'categories/small_show', locals: {category: @category = post.category} %>
                </div>
              </div>
              <% end %>
            <% end %>


        </div>
        </div>
      </div>
    </div>
    <!-- MAIN PAGE BODY END -->

    <!-- FOOTER -->
    <nav class="navbar navbar-light bg-primary navbar-fixed-bottom">

        <%= link_to "ANALYTICS", analytics_path, class: 'btn bg-primary text-light'%>

    </nav>

  </body>
</html>