railsprojectmodeapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :posts

  resources :sessions

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :categories

  resources :comments

  resources :likes

  resources :user_categories

  resources :mod_categories

  get '/modrequest', to: 'mod_categories#show'

  get '/analytics', to: 'analytics#index'

  get '/analytics/user', to: 'analytics#show', as: 'analytic'

  root 'posts#index'
end

railsprojectmodeapp/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user
  has_many :likes
  has_many :comments

  validates :title, :content, :category, presence: true

  def post_time
    if self.updated_at > self.created_at
      "edited on #{self.updated_at.strftime("%b %d, %Y")}" if self.updated_at > self.created_at
    else
      "posted on #{self.created_at.strftime("%b %d, %Y")}"
    end
  end

  def self.normal_posts
    self.all.select {|post| !post.category.market}
  end

  def self.market_posts
    self.all.select {|post| post.category.market}
  end

  def self.top_posts(arg)
    arg.sort_by{|x| x.likes.count}.reverse.take(4)
  end

  def summary
    if self.content.size > 150
      "#{self.content[0..150]} ..."
    else
      self.content
    end
  end

  def likes_count
    self.likes.count
  end

  def comments_count
    self.comments.count
  end


end

railsprojectmodeapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.top_posts(Post.normal_posts)
    if params[:type]

      if params[:type] == 'market'
        @type = 'market'
        @posts = Post.top_posts(Post.market_posts)
      end

    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = Post.new(post_params)
    @post.category = Category.find_by(name: params[:post][:category])

    if @post.save
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      redirect_to new_post_path
    end

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :post_type, :link, :user_id)
  end
end

railsprojectmodeapp/app/views/posts/_show_market.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">

        <%= link_to @post.user.username, user_path(@post.user) %>
        <% if @post.user.admin == true%>
          | admin |
        <%end%>

        is selling

        <span class="card-title"><%= link_to @post.title, post_path(@post), class: 'text-dark' %></span>



        <br>
        <%= link_to @post.category.name, category_path(@post.category) %><br>

        Contact Info: <br>
        Email: <%= @post.user.email %><br><br>
        <%= @post.likes.count %> likes<br>

        <p><%= @post.summary %></p>
      </div>
      <div class="card-action">

      </div>
    </div>
  </div>
</div>

railsprojectmodeapp/app/views/posts/_small_show.html.erb
<h5><%= @post.title %></h5>
<p class="pb-1"><%= @post.post_time %></p>
<%= "#{@post.likes_count} likes" %><br>
<%= "#{@post.comments_count} comments" %><br>

railsprojectmodeapp/app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-1.5">
    <%= button_to 'Top Posts', posts_path, method: 'get', class: 'btn bg-white border ml-3' %>
  </div>
    <div class="col-md-1">
    <%= button_to 'Top Market', posts_path, method: 'get', params: {type: 'market'}, class: 'btn bg-white border' %>
  </div>
</div>
<% if !@type %>
<div class="row">
  <% Category.all.select{|x| !x.market}.sample(4).each do |cate| %>
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title"><h1><%= link_to cate.name, category_path(cate) %></h1>
        <div class="card-text">

          <% @posts[0..1].each do |post| %>
          <div class="card">
            <div class="card-body">
              <div class="card-title">
                <strong><%= link_to post.title, post_path(post)%></strong><br>
                <%= post.summary%><br><br>
              </div>
              <div class="card-footer border">
                Lastest comment: <br>
                <%= post.comments.last.content[0..150] %>
              </div>
            </div>
          </div>
          <br>
          <% end %>


        </div>
      </div>
    </div>
    <br>

  </div>
  <% end %>
</div>
<% end %>

<!-- MARKET POSTS -->
<% if @type == 'market' %>
    <% Category.market_categories.sample(5).each do |cate| %>
    <div >
    <h1 class="ml-1"><%= link_to cate.name, category_path(cate) %></h1>
    <div class="row ml-1">
      <% @posts.each do |post| %>
        <div class="col-md-3 border">
          <%= link_to post.title, post_path(post)%><br>
          <%= post.summary%>
        </div>
        <br><br>
      <% end %>
    </div>
<br>
  </div>


  <% end %>
<% end %>

railsprojectmodeapp/app/views/posts/new.html.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

<!-- NEW TEXT FORM -->
<div class="card">
  <div class="card-body">
    <div class="card-title">
      <strong>Create a text post</strong>
    </div>
    <div class="card-text">
      <%= form_for @post do |f|%>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Title", class: 'form-control', required: true%>
        </div>
        <%= f.text_area :content, placeholder: "Content", rows: 7, class: 'form-control mb-3'%>

        <%= f.text_field :category, placeholder:"Category", id: 'moo', class: 'form-control mb-3', list: 'cata-list' %>
          <datalist id="cata-list">
            <% Category.all.each do |cata| %>
              <option value="<%= cata.name %>"></option>
            <% end %>
          </datalist>

          <%= f.hidden_field :post_type, value: "text" %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        <%=f.submit "Submit Post", class: 'btn-block bg-light'%>
      <%end%>
    </div>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md text-center">
    <strong>OR</strong>
  </div>
</div>

<br>

<!-- NEW URL FORM -->
<div class="card mb-4">
  <div class="card-body">
    <div class="card-title">
      <strong>Create a link post</strong>
    </div>
    <div class="card-text">
      <%= form_for @post do |f|%>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Title", class: 'form-control', required: true%>
        </div>
        <div class="form-group">
          <%= f.text_field :link, placeholder: "URL", class: 'form-control', required: true%>
        </div>

        <%= f.text_field :category, placeholder:"Category", class: 'form-control mb-3', list: 'cata-list' %>
          <datalist id="cata-list">
            <% Category.all.each do |cata| %>
              <option value="<%= cata.id %>"></option>
            <% end %>
          </datalist>

          <%= f.hidden_field :post_type, value: "url" %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        <%=f.submit "Submit Post", class: 'btn-block bg-light'%>
      <%end%>
    </div>
  </div>
</div>

railsprojectmodeapp/app/views/posts/show.html.erb
<% if @post.category.market %>
  <%= render 'posts/show_market', locals: {post: @post, user: @post.user} %>
<% else %>


<%= @post.title %><br><br>
<%= @post.content %><br>
<%= @post.likes.count %> likes<br>

<% if logged_in? %>
  <% if !@post.likes.any? {|like| like.user == current_user } %>
    <%= button_to "Like", {controller: "likes", action: "create", post_id: @post.id, user_id: current_user.id} %>
  <% else %>
    <%= button_to "Unlike", {controller: "likes", action: "destroy", post_id: @post.id, user_id: current_user.id}, method: 'delete' %>
  <% end %>
<% end %>


<a href="<%= @post.link %>"><%= @post.link %></a>
<br>
<%= link_to @post.user.username, user_path(@post.user)%>
  <% if @post.user.admin == true%>
    | admin
    <%end%>
<br>


<%= link_to @post.category.name, category_path(@post.category)%>
<br><br>

<% if logged_in? %>
  <%= render file: 'comments/new', locals: {post_id: @post.id} %>
<% else %>
  <h5>Please login or signup to comment</h5>
<% end %>

<% @post.comments.reverse.each do |comm| %>

  <strong><%= link_to comm.user.username, user_path(comm.user) %></strong>

  <%if comm.user.mod_categories.any? {|x| x.category_id == @post.category_id }%> | moderator |
  <%elsif comm.user.admin == true%>
    | admin |
  <%end%>

  <%= comm.created_at %><br>
  <%= comm.content %>
  <br><br>

  <% if comm.user == current_user %>
    <%= link_to "Edit", edit_comment_path(comm) %>
    <%= link_to "Delete", comment_path(comm), method: 'delete' %>

    <br><br>
  <% elsif logged_in? && current_user.admin == true || logged_in? && current_user.mod_categories.any? {|x| x.category_id == @post.category_id} %>
    <%= link_to "Delete", comment_path(comm), method: 'delete' %>
    <br><br>

  <% end %>

<% end %>

<% end %>