railsprojectmodeapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :posts

  resources :sessions

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :categories

  resources :comments

  resources :likes

  resources :user_categories

  resources :mod_categories

  get '/modrequest', to: 'mod_categories#show'

  get '/analytics', to: 'analytics#index'

  get '/analytics/user', to: 'analytics#show', as: 'analytic'

  root 'posts#index'
end

railsprojectmodeapp/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :likes
  has_many :comments
  has_many :posts
  has_many :user_categories
  has_many :categories, through: :user_categories
  has_many :mod_categories
  # has_many :categories, through: :mod_categories

  validates :username, :email, presence: true, uniqueness: true
  # validates :password, presence: true

  def liked_categories
    Post.all.select do |post|
      self.categories.include?(post.category)
    end
  end

  def posts_count
    self.posts.count
  end

  def likes_count
    self.likes.count
  end

  def comments_count
    self.comments.count
  end

  def member_since
    join_date = (((Time.now - self.created_at)/3600)/24)

    if join_date <= 1
      "Member for 1 day"
    else
      "Member for #{join_date.floor} days"
    end
  end

  def total_score
    self.likes.count
  end

  def uniq_score
    self.likes.map do |like|
      like.user
    end.uniq.count
  end

  def image_link
    case self.image
    when "default"
      "default.png"
    when "alligator"
      "alligator/#{self.color}.png"
    when "anteater"
      "anteater/#{self.color}.png"
    when "axolotl"
      "axolotl/#{self.color}.png"
    when "armadillo"
      "armadillo/#{self.color}.png"
    end
  end

  def moderated_categories
    if self.moderator == true
      self.mod_categories
    end
  end

  def is_moderating(cat)
    self.moderated_categories.any? do |x|
        x.category_id == cat.id
    end
  end


end

railsprojectmodeapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    #will show their posts/likes/etc
    if logged_in?
      @user = current_user
      @posts = @user.posts
    else
      redirect_to new_session_path
    end
    # @categories = @user.categories
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  def show
    #will show only account info
    @user = User.find(params[:id])
    if params[:show_type]
      @type = params[:show_type]
    end
    @market_posts = @user.posts.select {|post| post.category.market}
    @posts = @user.posts.select {|post| !post.category.market}
    @comments = @user.comments
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
  end

  private

  def user_params

    params.require(:user).permit(:username, :password, :password_confirmation, :email, :birth_date, :admin, :moderator, :image, :color)

  end

end

railsprojectmodeapp/app/views/users/_form.html.erb
<%= form_for @user do |f|%>
  <div class="row">
    <div class="col-md-10 offset-1">
      <%=f.text_field :username, placeholder: "Username", class: 'form-control' %><br>
    </div>
  </div>

  <div class="row ">
    <div class="col-md-5 offset-1">
      <%=f.password_field :password, placeholder: "Password", class: 'form-control' %>
    </div>
    <div class="col-md-5">
      <%=f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form-control' %><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 offset-1">
      <%=f.text_field :email, placeholder: "Email", class: 'form-control' %><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 offset-1">
      <%=f.date_field :birth_date, placeholder: "D.O.B.", class: 'form-control' %><br>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-10 offset-1">
      <%=f.submit "Create Account", class: "btn-block bg-light form-control"%>
    </div>
  </div>
<%end%>

railsprojectmodeapp/app/views/users/_small_show.html.erb
<% if @user == current_user %>
  <h5><%= link_to @user.username, user_path(@user) %></h5>
  <%= "total score: #{@user.total_score}" %><br>
  <%= "unique score: #{@user.uniq_score}" %><br>
  <%= link_to "Go to Profile", user_path(@user) %> |
  <%= link_to "Log out", logout_path, method: 'delete' %>
<% end %>

railsprojectmodeapp/app/views/users/edit.html.erb
<% if current_user.admin == true %>
  <h2>Change mod status</h2>

  <%= form_for @user do |f|%>

  <%= f.radio_button(:moderator, true) %>
  <%= f.label(:moderator, "Moderator") %>
  <%= f.radio_button(:moderator, false) %>
  <%= f.label(:moderator, "Regular User") %>

    <%=f.submit%>
  <%end %>

<%else%>

<h2>Edit Your Account</h2>
<%= form_for @user do |f|%>

  <%= f.select :image, options_for_select(["armadillo","axolotl","anteater","alligator"]) %><br>

  <%= f.select :color, options_for_select(["blue","red","yellow","green"]) %><br>

  <%=f.text_field :username, placeholder: "Username"%><br>

  <%=f.password_field :password, placeholder: "Password"%><br>

  <%=f.text_field :email, placeholder: "Email"%><br>

  <%=f.date_field :birth_date%><br>

  <%=f.submit%>

<%end%>
<%end%>

railsprojectmodeapp/app/views/users/index.html.erb
<% @user.liked_categories.each do |post| %>
  <%= post.title %><br>
  <%= post.content %><br><br>
<% end %>

railsprojectmodeapp/app/views/users/new.html.erb
<h2>Create Your Account</h2><br>

<%= render 'users/form', locals: {user: @user} %>

railsprojectmodeapp/app/views/users/show.html.erb
<div class="row">
  <div class="col-md-9 offset-2 text-center">

  <h1><%=@user.username%></h1>
    <% if @user.admin == true%>
       <h3>admin</h3>
    <%elsif @user.moderator == true%>
        <h3>mod of:
        <% @user.moderated_categories.each do |mod|%>
          <%= link_to mod.category.name, category_path(mod.category.id)%>
        <%end%>
        </h3>
    <%end%>


  <!-- BUTTON TO EDIT A USER -->

  <% if logged_in? && current_user.admin == true && !current_page?(user_path(current_user)) %>
    <%= button_to "Change Mod Status", edit_user_path(@user), method: 'get' %>
  <%end%>


<% if @user == current_user %>
  <h4>Birthday: <%=@user.birth_date.strftime("%b %e, %Y")%></h4>
  <h4>Email: <%=@user.email%></h4>
<% end %>
<br>
<div class="row">
    <div class="col-md-1.5">
    <%= button_to "Posts", user_path(@user), params: {show_type: "posts"}, method: 'get', class: 'btn bg-white border ml-3' %>
    </div>

    <div class="col-md-1.5">
    <%= button_to "Market Posts", user_path(@user), params: {show_type: "market"}, method: 'get', class: 'btn bg-white border ml-3' %>
    </div>

    <div class="col-md-1.5">
    <%= button_to "Likes", user_path(@user), params: {show_type: "likes"}, method: 'get', class: 'btn bg-white border ml-3' %>
    </div>

    <div class="col-md-1.5">
    <%= button_to "Comments", user_path(@user), params: {show_type: "comments"}, method: 'get', class: 'btn bg-white border ml-3' %>
    </div>

    <% if @user == current_user %>
      <%= button_to "Edit Account", edit_user_path(@user), method: 'get', class: 'btn bg-white border ml-3' %>
      <%= button_to "My Analytics", analytic_path, method: 'get', class: 'btn bg-white border ml-3' %>
    <%end%>
</div>

<% if @type == "posts" %>
  <h5>POSTS</h5>
  <% @posts.reverse.each do |post| %>
    <%=link_to post.title, post_path(post)%> <%= post.post_time %><br>
    <%=link_to post.category.name, category_path(post.category)%>
    <br><br>
  <%end%>
<% end %>

<% if @type == "market" %>
  <h5>SELLING</h5>
  <% @market_posts.each do |post| %>
    <%= render file: 'posts/show', locals: {post: @post = post} %>
    <br><br>
  <%end%>
<% end %>

<% if @type == "likes" %>
<h5>LIKES</h5>
  <% @user.likes.each do |like| %>
    <%= link_to like.post.title, post_path(like.post) %><br>
  <% end %>
<% end %>

<% if @type == "comments" %>
  <h5>COMMENTS</h5>
  <% @comments.each do |comment| %>
    <%=link_to comment.post.title, post_path(comment.post)%><br>
    <%= comment.content %><br><br>
  <%end%>
<% end %>
</div>
</div>