railsprojectmodeapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :posts

  resources :sessions

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :categories

  resources :comments

  resources :likes

  resources :user_categories

  resources :mod_categories

  get '/modrequest', to: 'mod_categories#show'

  get '/analytics', to: 'analytics#index'

  get '/analytics/user', to: 'analytics#show', as: 'analytic'

  root 'posts#index'
end

railsprojectmodeapp/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true

end

railsprojectmodeapp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    @comment = Comment.create!(comment_params)
    redirect_to(request.env['HTTP_REFERER'])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to post_path(@comment.post)
    else
      flash[:error] = @comment.errors.full_messages
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to(request.env['HTTP_REFERER'])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
end

railsprojectmodeapp/app/views/comments/edit.html.erb
<%= form_for @comment do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

railsprojectmodeapp/app/views/comments/new.html.erb
<%= form_tag comments_path do  %>
  <%= text_area_tag 'comment[content]', nil, class: 'form-control', rows: 5 %>
  <%= hidden_field_tag 'comment[post_id]', @post.id %>
  <%= hidden_field_tag 'comment[user_id]', current_user.id %>

  <%= submit_tag "Add Comment", class: 'btn-block bg-light form-control mb-5 mt-3'%>
<% end %>